version: "3.9"
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 3000:3000
    depends_on:
       -pg
    volumes:
      - ./api/src/usr/app/src
    environment:
      PG_CONNECTION_STRING: postgres://admin:dev5@dev5_db:5432/dev5_api
    
  
  pg: 
    image: postgres:latest
    ports:
     -5432:5432
    environment: 
     -POSTGRES_DB
     -POSTGRES_USER
     -POSTGRES_PASSWORD

rediss:
 images:rediss
